apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: ollama
  name: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ai.ollama.storage }}
