apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: openedai-speech-server
  name: openedai-speech-server-voices-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.ai.openedaiSpeechServer.voicesStorage }}
