apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: ghost-db
  name: ghost-db-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.blog.db.storage }}
