apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: ghost
  name: ghost-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.blog.ghost.storage }}
