apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: vector
  name: vector-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.core.vector.storage }}
