apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: db
  name: db-migrations-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
