apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: db
  name: db-ssl-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.core.db.sslStorage }}
