apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: supavisor
  name: supavisor-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
