apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    service: redis
  name: redis
spec:
  replicas: {{ int .Values.ecommerce.redis.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        service: redis
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - redis-server
          image: redis
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 30
            periodSeconds: 1
            timeoutSeconds: 3
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
