apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: meilisearch
  name: meilisearch-data-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
