apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: nginx
  name: nginx-ssl-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nginx.sslStorage }}
