apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: {{ int .Values.nginx.replicas }}
  selector:
    matchLabels:
      service: nginx
  template:
    metadata:
      labels:
        service: nginx
    spec:
      initContainers:
      - name: init-nginx
        image: nginx:latest
        command:
          - /bin/sh
          - -c
          - |
            ls /etc/nginx
            cp -r /etc/nginx/* /tmp/etc/nginx
            rm /tmp/etc/nginx/nginx.conf
            while [ ! -e /tmp/etc/nginx/nginx.conf ] || [ ! -s /tmp/etc/nginx/nginx.conf ]; do 
              echo 'Waiting for all copied files...'
              sleep 10
            done
        volumeMounts:
          - mountPath: /tmp/etc/nginx
            name: nginx-config-volume
            subPath: nginx
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
          - mountPath: /etc/nginx
            name: nginx-config-volume
            subPath: nginx
        ports:
        - containerPort: 80
      restartPolicy: Always
      volumes:
      - name: nginx-config-volume
        persistentVolumeClaim:
            claimName: nginx-config-volume-claim