apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: nginx
  name: nginx-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nginx.configStorage }}
