apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: minio
  name: minio-data-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
