apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    service: rest
  name: rest
spec:
  strategy:
    type: Recreate
  replicas: {{ int .Values.core.rest.replicas }}
  selector:
    matchLabels:
      service: rest
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        service: rest
    spec:
      initContainers:
        - name: init-rest
          image: curlimages/curl
          command: [
            'sh', 
            '-c', 
            'until curl -fsSL -m 2 db:5432 > /dev/null 2>&1 || [ $? -eq 52 ]; do echo waiting for postgres; sleep 2; done;'
          ]
      containers:
        - args:
            - postgrest
          env:
            - name: PGRST_DB_ANON_ROLE
              value: anon
            - name: PGRST_DB_USE_LEGACY_GUCS
              value: "false"
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: PGRST_DB_URI
            - name: PGRST_DB_SCHEMAS
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: PGRST_DB_SCHEMAS
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: PGRST_JWT_SECRET
            - name: PGRST_APP_SETTINGS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: PGRST_APP_SETTINGS_JWT_SECRET
            - name: PGRST_APP_SETTINGS_JWT_EXP
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: JWT_EXPIRY
          image: postgrest/postgrest:v12.2.0
          name: supabase-rest
          ports:
            - containerPort: 3000
      restartPolicy: Always
