apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: open-webui
  name: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
