apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    service: standalone
  name: standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      service: standalone
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        service: standalone
    spec:
      initContainers:
      - name: init-milvus-standalone
        image: milvusdb/milvus:latest-gpu
        command:
          - /bin/sh
          - -c
          - |
            while [ ! -e /milvus/configs/milvus.yaml ] || [ ! -s /milvus/configs/milvus.yaml  ]; do 
              echo 'Waiting for all copied files...'
              sleep 10
            done
        volumeMounts:
          - mountPath: /milvus/configs
            name: standalone-volume
            subPath: configs
      containers:
        - args:
            - milvus
            - run
            - standalone
          env:
            - name: ETCD_ENDPOINTS
              value: etcd:2379
            - name: MINIO_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MINIO_ADDRESS
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MINIO_ROOT_USER
          image: milvusdb/milvus:latest-gpu
          name: milvus-standalone
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          ports:
            - containerPort: 19530
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          volumeMounts:
            - mountPath: /milvus/configs
              name: standalone-volume
              subPath: configs
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu
                operator: Exists
      volumes:
        - name: standalone-volume
          persistentVolumeClaim:
            claimName: standalone-volume-claim
