apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: standalone
  name: standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: standalone
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: standalone
    spec:
      containers:
        - args:
            - milvus
            - run
            - standalone
          env:
            - name: ETCD_ENDPOINTS
              value: etcd:2379
            - name: MINIO_ADDRESS
            - name: MINIO_ROOT_PASSWORD
            - name: MINIO_ROOT_USER
          image: milvusdb/milvus:latest-gpu
          name: milvus-standalone
          ports:
            - containerPort: 19530
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          volumeMounts:
            - mountPath: /milvus/configs/milvus.yaml
              name: standalone-cm1
              subPath: milvus.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: milvus.yaml
                path: milvus.yaml
            name: standalone-cm1
          name: standalone-cm1
