apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: standalone
  name: standalone-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
