apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: storage
  name: storage-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
