apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    service: meilisearch
  name: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meilisearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: meilisearch
    spec:
      containers:
        - env:
            - name: MEILI_DB_PATH
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MEILI_DB_PATH
            - name: MEILI_ENV
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MEILI_ENV
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MEILI_MASTER_KEY
            - name: MEILI_NO_ANALYTICS
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MEILI_NO_ANALYTICS
          image: getmeili/meilisearch:latest
          livenessProbe:
            exec:
              command:
                - curl -X GET 'http://localhost:7700/health'
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          name: meilisearch
          ports:
            - containerPort: 7700
              protocol: TCP
          volumeMounts:
            - mountPath: /data.ms
              name: meilisearch-data
      restartPolicy: Always
      volumes:
        - name: meilisearch-data
          persistentVolumeClaim:
            claimName: meilisearch-data-volume-claim
