apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: medusa-server
  name: medusa-server-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
