apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: standalone
  name: standalone-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ai.standalone.storage }}
