apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: kong
  name: kong-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.core.kong.storage }}
