apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: imgproxy
  name: imgproxy-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.core.imgproxy.storage }}
