apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: nginx-core
  name: nginx-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nginx.configStorage }}
