services:
  minio:
    image: minio/minio
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    hostname: 127.0.0.1
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - ./volumes/storage:/data:z
    deploy:
      placement:
        constraints: [node.labels.s3 == manager]

  minio-createbucket:
    image: minio/mc
    restart: on-failure
    depends_on:
      - 'minio'
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set supa-minio ${MINIO_ADDRESS} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb supa-minio/stub;
      exit 0;
      "
