apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    service: medusa-server
  name: medusa-server
spec:
  type: ClusterIP
  ports:
    - name: "9010"
      port: 9010
      targetPort: 9010
  selector:
    service: medusa-server
